### ISSUE TITLE
Youtube playlist

### ISSUE THREAD

**Issue by edap** [subogero/omxd#36]
Hello, I was wondering if it's possible to run a playlist of youtube videos. 
As "playlist" i do not mean a YouTube playlist, but a text file containing youtube's video URLs

**Comment by subogero** [comment]
Not yet, but I'm working on it. I'll get back to you when I have something.

Originally omxplayer was not able to use the necessary YouTube cookies, so the way to play YouTube is to stream the video by curl into a temporary FIFO, and let omxplayer play the FIFO file.

**Comment by subogero** [comment]
In the meantime, see my other project, u2b. It can play YouTube via omxd. But still, no playlists...

**Comment by subogero** [comment]
So far, you can use `u2b` to extract YouTube streams

    u2b u0s Valentino Rossi

will print the stream URL of the first search hit for Valentino Rossi. Then you can

    omxd A '<URL>'

which will add it to the playlist. I'm working on u2b to be able to do thius directly.
