### ISSUE TITLE
Volume level resets for every video

### ISSUE THREAD

**Issue by OMID-313** [subogero/omxd#40]
Hi @subogero .
Thanks for this great daemon.

I'm having a trouble using the volume commands:
The `omxd +` and `omxd -` functions increase and decrease the volume to desired level.
But after the current video has finished, and the next video is started, the volume level gets reset to default level.

Is there anyway to restore the volume level for all the videos in the playlist !?

**Comment by subogero** [comment]
Unfortunately the volume commands only go to the active omxplayer instance and are not stored by the daemon.

**Comment by OMID-313** [comment]
Is there anyway to do this ?
Any help/suggestions?

**Comment by subogero** [comment]
Open another issue for "persistent volume" and I'll look into it.
