### ISSUE TITLE
omxd install script not creating /usr/share/doc/omxd/ directory

### ISSUE THREAD

**Issue by priiduonu** [subogero/omxd#42]
root@raspberrypi:~/omxd# make install
./preinst
cp omxd /usr/bin
IFS=''; while read i; do [ "$i" = HELP ] && sed -n '/rpyt/,$p' README; echo "$i"; done <rpyt >/usr/bin/rpyt
chmod +x /usr/bin/rpyt
cp omxd.1 /usr/share/man/man1/
cp rpyt.1 /usr/share/man/man1/
cp init      /usr/share/doc/omxd/
cp: cannot create regular file ‘/usr/share/doc/omxd/’: Not a directory
Makefile:24: recipe for target 'install' failed
make: *** [install] Error 1

root@raspberrypi:~/omxd# grep cp Makefile 
	cp omxd $(DESTDIR)/usr/bin
	cp omxd.1 $(DESTDIR)/usr/share/man/man1/
	cp rpyt.1 $(DESTDIR)/usr/share/man/man1/
	cp init      $(DESTDIR)/usr/share/doc/omxd/
	cp logrotate $(DESTDIR)/usr/share/doc/omxd/
	cp -rt $(REL)/omxd-$(TAG) *; \
	cp -f $(REL)/omxd_$(TAG).tar.gz $(REL)/omxd_$(TAG).orig.tar.gz
	cp preinst postinst prerm postrm $(DEB)
root@raspberrypi:~/omxd# 

because /usr/share/doc/omxd directory has not been created by install script, also the postinst script fails

(omxd cloned from github)

regards,
priiduonu

**Comment by subogero** [comment]
Is this the newest Raspbian?

**Comment by priiduonu** [comment]
yes, jessie

**Comment by subogero** [comment]
The bastards at Debian broke all my projects, because they insisted on changing everything...

**Comment by subogero** [comment]
Does the directory `/usr/share/doc/` exist before or after `make install`?

**Comment by priiduonu** [comment]
/usr/share/doc exists (it has several subdirectories) but /usr/share/doc/omxd/ doest not exist. I think you should create it yourself.

**Comment by subogero** [comment]
OK. But why did it work with Wheezy?

**Comment by subogero** [comment]
Or why did it work *ever*? The Makefile is clearly wrong... Anyway, I'll fix it.

**Comment by priiduonu** [comment]
I have never used the /etc/init.d/omxd script for starting the player, I only discovered this bug today.

**Comment by subogero** [comment]
I realized what the problem is. If you install from the deb package, its `omxd.dirs` file specifies `/usr/share/doc/omxd`, so it's created automatically before the deb package runs `make install`.

**Comment by priiduonu** [comment]
thanks and keep up the good work!
