### ISSUE TITLE
Can't control the omxplayer by dbus

### ISSUE THREAD

**Issue by tzraeq** [subogero/omxd#48]
Hi,
    I can't control omxplayer process by dbus-send command, which started by omxd service on raspbain.

    Is there any other solutions?

**Comment by subogero** [comment]
It was never meant to be usable. Usually `omxd` starts 2 `omxplayer` processes, the 2nd paused at the beginning of the next track. How would dbus handle that? Plus it would totally screw up `omxd`'s timekeeping and status.

WONTFIX
