### ISSUE TITLE
Why I cannot control omxplayer through DBUS when I run omxd as a init service?

### ISSUE THREAD

**Issue by tzraeq** [subogero/omxd#49]
When I run a omxd service ,the omxplayer generate the dbus connection but I cannot connect to the session. Is there any other solutions?

**Comment by subogero** [comment]
My knowledge of dbus is zero. I can't help you. Even if it worked, it would screw up omxd's status, because stuff would happen with the omxplayer instances outside of omxd's knowledge or control. A absolutely and positively refuse to to deal with Dbus.

**Comment by tzraeq** [comment]
If the omxd control the omxplayer through by dbus but not through the the keyboard char,and give some api, this will fixed

**Comment by tzraeq** [comment]
omxplayer repo has a dbuscontrol.sh,it is so easy.

**Comment by subogero** [comment]
If it's easy then do it yourself. I'm looking forward to your pull request.

**Comment by tzraeq** [comment]
I think only the play/pause action will screw up the omxd status.
Or , if you can tell me the method to open the second omxplayer and pause at the beginning,I think I can fix it.

**Comment by subogero** [comment]
Do you realise that it's Sunday and I'm not your emloyee?

**Comment by tzraeq** [comment]
Sorry , it doesn't means that I want you to reply immediatly.
Have a good weekend!
