### ISSUE TITLE
Videos freeze when updating the playlist directory

### ISSUE THREAD

**Issue by OMID-313** [subogero/omxd#54]
I have set the omxd to play all the videos in a folder.

But, every time I delete all those files and replace them with new video files and reboot the system, the 1st and 2nd videos begin to play simultaneously, then the `No HDMI Signal` appears on the TV, and then freeze.

This happens only once after replacing new files in the directory and rebooting the system. It doesn't happen any more other times.

I didn't have this problem when using wheezy and `rc.local`. But after updating to Jessie and using systemd, this problem happens.

The following are the new codes I use (instead of `rc.local`):

**_/lib/systemd/system/myboot.service :_**

```
[Unit]
Description=Play a playlist in loop automatically on boot

[Service]
Type=idle
ExecStart=/path/to/myscript.sh

[Install]
WantedBy=multi-user.target
```

**_/path/to/myscript.sh :_**

```
clear

sleep 5

clear

systemctl stop omxd
sleep 0.5
systemctl start omxd
sleep 0.5

clear

omxd X
omxd j
omxd O --blank
omxd O --no-osd
omxd A /usermedias

clear

sleep 3
omxd -
sleep 0.2
omxd -
sleep 0.2
omxd -
sleep 0.2
omxd -
sleep 0.2
omxd -

clear
```

**Comment by OMID-313** [comment]
Problem solved by commenting the last 10 lines (decreasing the volume)
```
...
clear

#sleep 3
#omxd -
#sleep 0.2
#omxd -
#sleep 0.2
#omxd -
#sleep 0.2
#omxd -
#sleep 0.2
#omxd -

clear
...
```

**Comment by subogero** [comment]
I'll try to reproduce it.
