### ISSUE TITLE
effects on video transitions

### ISSUE THREAD

**Issue by rifotu** [subogero/omxd#65]
Hello,

Can omxd do effects like fade out during video transitions?

**Comment by subogero** [comment]
Fading out the audio is supported by `omxplayer` via hotkey. But I don't know about fading out the video.

Theoretically it's possible, but `omxd` at the moment only reacts on user inputs and exiting `omxplayer` child processes. So it does not anticipate the end of the track.

So this feature would necessitate a periodic timer event source in omxd, which is quite complicated.

**Comment by rifotu** [comment]
hello,

thanks for the answer. Is it then possible to have the fade out effect happening on a user input? For example when a user presses a button, a seperate video starts playing but the transition is not instantaneous and instead fade out effect happens.

**Comment by subogero** [comment]
Do you want video or audio fadeout?

**Comment by rifotu** [comment]
I would like to have video fadeout if possible. Audio fadeout would be nice but not really required.

**Comment by subogero** [comment]
Could you please investigate whether `omxplayer` supports this? If not, no chance. Please note that `omxd` does not play back anything, it merely manages `omxplayer` instances.

**Comment by rifotu** [comment]
so sad :(

the guys at omxplayer repository said that they don't support fadeout effects

**Comment by subogero** [comment]
Great sadness for you,
Great relief for me...
