### ISSUE TITLE
make install error "Failed to stop omxd.service"

### ISSUE THREAD

**Issue by cryptojatt** [subogero/omxd#77]
I'm following the install guide and I've run make install but I get this in the output:

./preinst
Running omxd preinst
Failed to stop omxd.service: Unit omxd.service not loaded.
Unknown operation 'omxd'.
cp omxd /usr/bin
cp: cannot create regular file ‘/usr/bin/omxd’: Text file busy
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 1

Any ideas?

**Comment by harpss1ngh** [comment]
Edit: Nevermind, not sure how but omxd was running. Did a killall omxd and it worked.

**Comment by harpss1ngh** [comment]
I know why it doesn't work. The postinst recipe in the make install doesn't work. I think the makeinstall fails after the preinst script. The systemd service and other files aren't created and I have to manually copy them and create the symlinks

**Comment by subogero** [comment]
Are you running these steps manually? All you should do is

    apt install omxd

**Comment by subogero** [comment]
Next question. Are you running those comands as root?
