### ISSUE TITLE
Feature Request: Allow network streams

### ISSUE THREAD

**Issue by cryptojatt** [subogero/omxd#78]
Thanks for the work you have put into this so far. I run omxplayer in a cron job with an rtsp stream from a webcam, is it possible to use omxd to play a stream?

e.g. I run something like this in a shell with omxplayer:

/usr/bin/omxplayer -b -y -w -r rtsp://user:pass@111.222.333.444 "$1"

**Comment by subogero** [comment]
Anything that can be played with `omxplayer`, can be played with `omxd`. Sometimes more, especially with older versions of `omxplayer` that could not handle http cookies. `omxd` streams those via `curl` and a FIFO file to `omxplayer` and `curl` handles to cookies.

**Comment by subogero** [comment]
If you must use the options `-b -y -w -r`, you can also tell `omxd` to apply them to playlist items. See command `O`.

What is `"$1"`?
